/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import kelas.prestasi;
/**
 *
 * @author Sukma Nur
 */
public class panelPrestasi extends javax.swing.JPanel {

    /**
     * Creates new form panelPrestasi
     */
    public panelPrestasi() {
        initComponents();
         load_table_prestasi();
    }
    
      public void load_table_prestasi(){
    prestasi ps = new prestasi();
    DefaultTableModel model = ps.showprestasi();
    table_prestasi.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_tambah = new javax.swing.JButton();
        c_carianggota = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prestasi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(250, 240, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 22, 22));
        jLabel1.setText("PRESTASI ANGGOTA");

        b_tambah.setBackground(new java.awt.Color(0, 204, 51));
        b_tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_tambah.setText("Tambah");
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        c_carianggota.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Anggota"));
        c_carianggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_carianggotaActionPerformed(evt);
            }
        });
        c_carianggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_carianggotaKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(140, 22, 22));
        jPanel2.setPreferredSize(new java.awt.Dimension(719, 515));

        table_prestasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_prestasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_prestasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_prestasi);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tabel Prestasi Anggota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_tambah)
                                .addGap(18, 18, 18)
                                .addComponent(c_carianggota, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_tambah)
                    .addComponent(c_carianggota, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        // TODO add your handling code here:
        popUpTambahPrestasi popup = new popUpTambahPrestasi(this);
        popup.setVisible(true);
        popup.tampilanTambah();
    }//GEN-LAST:event_b_tambahActionPerformed

    private void c_carianggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_carianggotaActionPerformed

            // TODO add your handling code here:
        
    }//GEN-LAST:event_c_carianggotaActionPerformed

    private void table_prestasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_prestasiMouseClicked
        // TODO add your handling code here:
         int baris = table_prestasi.rowAtPoint(evt.getPoint());
        
        if (baris >=0){
            String ID_prestasi = table_prestasi.getValueAt(baris, 1).toString();
            Object peringkatobj = table_prestasi.getValueAt(baris, 2).toString();
            Object tingkatobj = table_prestasi.getValueAt(baris, 3).toString();
            Object tglobj = table_prestasi.getValueAt(baris, 4);
            Object namaAnggotaobj = table_prestasi.getValueAt(baris, 5).toString();
            
            //mengonversi objek menjadi string, jika null maka hasilnya null atau string kosong
            
            String peringkat = (peringkatobj != null)? peringkatobj.toString():null;
            String tingkat = (tingkatobj != null)? tingkatobj.toString():null;
            String tgl = (tglobj != null)? tglobj.toString():null;
            String namaAnggota = (namaAnggotaobj != null)? namaAnggotaobj.toString():null;
            
            
            popUpTambahPrestasi edit = new popUpTambahPrestasi(this);
            edit.setVisible(true);
            edit.setData(ID_prestasi, peringkat, tgl, namaAnggota,tingkat);
            edit.tampilanUbah();
          
        }
    }//GEN-LAST:event_table_prestasiMouseClicked

    private void c_carianggotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_carianggotaKeyReleased
        // TODO add your handling code here:
        String kataKunci = c_carianggota.getText();
        prestasi ps = new prestasi();
        DefaultTableModel model = ps.filterTablePrestasi(kataKunci);
        table_prestasi.setModel(model);
    }//GEN-LAST:event_c_carianggotaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_tambah;
    private javax.swing.JTextField c_carianggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_prestasi;
    // End of variables declaration//GEN-END:variables
}
