/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import kelas.laporan;
import kelas.pelatih;

/**
 *
 * @author Sukma Nur
 */
public class PanelPelatih extends javax.swing.JPanel {

    /**
     * Creates new form PanelPelatih
     */
    public PanelPelatih() {
        initComponents();
        loadTablePelatih();
    }

    public void loadTablePelatih() {
        pelatih plt = new pelatih();
        DefaultTableModel model = plt.showPelatih();
        table_pelatih.setModel(model);
        plt.aturTable(table_pelatih);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        tCariPelatih = new javax.swing.JTextField();
        bReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pelatih = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bExport = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(950, 650));

        jPanel1.setBackground(new java.awt.Color(250, 240, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 22, 22));
        jLabel1.setText("DATA PELATIH");
        jLabel1.setPreferredSize(new java.awt.Dimension(12, 16));

        bTambah.setBackground(new java.awt.Color(0, 204, 0));
        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bTambah.setText(" Tambah : ");
        bTambah.setPreferredSize(new java.awt.Dimension(89, 35));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        tCariPelatih.setForeground(new java.awt.Color(181, 181, 181));
        tCariPelatih.setText("Nama Pelatih");
        tCariPelatih.setPreferredSize(new java.awt.Dimension(86, 35));
        tCariPelatih.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCariPelatihFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCariPelatihFocusLost(evt);
            }
        });
        tCariPelatih.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariPelatihKeyReleased(evt);
            }
        });

        bReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(140, 22, 22));

        table_pelatih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_pelatih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pelatihMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pelatih);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 240, 230));
        jLabel2.setText("Tabel Data Pelatih");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        bExport.setBackground(new java.awt.Color(255, 51, 51));
        bExport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExport.setForeground(new java.awt.Color(255, 255, 255));
        bExport.setText("Export PDF");
        bExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(tCariPelatih, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(bReset)))))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bExport)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCariPelatih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReset))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bExport)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        popUpTambahPelatih pelatih = new popUpTambahPelatih(this);
        pelatih.setVisible(true);
        pelatih.tampilanTambah();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        tCariPelatih.setText("Nama Pelatih");
        tCariPelatih.setForeground(Color.GRAY);
        loadTablePelatih();
    }//GEN-LAST:event_bResetActionPerformed

    private void tCariPelatihKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariPelatihKeyReleased
        String kataKunci = tCariPelatih.getText();
        pelatih plt = new pelatih();
        DefaultTableModel model = plt.filterTable(kataKunci);
        table_pelatih.setModel(model);
        plt.aturTable(table_pelatih);
    }//GEN-LAST:event_tCariPelatihKeyReleased

    private void table_pelatihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pelatihMouseClicked
        int baris = table_pelatih.rowAtPoint(evt.getPoint());

        String id = table_pelatih.getValueAt(baris, 1).toString();
        Object namaObjek = table_pelatih.getValueAt(baris, 2);
        Object kontakObjek = table_pelatih.getValueAt(baris, 3);
        Object sabukObjek = table_pelatih.getValueAt(baris, 4);

        // Mengonversi objek menjadi string, jika null maka hasilnya null atau string kosong
        String nama = (namaObjek != null) ? namaObjek.toString() : null;
        String kontak = (kontakObjek != null) ? kontakObjek.toString() : null;
        String sabuk = (sabukObjek != null) ? sabukObjek.toString() : null;

        popUpTambahPelatih pelatih = new popUpTambahPelatih(this);
        pelatih.tampilData(id, nama, kontak, sabuk);
        pelatih.setVisible(true);
        pelatih.tampilanEdit();
    }//GEN-LAST:event_table_pelatihMouseClicked

    private void bExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportActionPerformed
        String namaPelatih = tCariPelatih.getText();
        laporan lap = new laporan();
        lap.generateLaporanPelatih(namaPelatih);
    }//GEN-LAST:event_bExportActionPerformed

    private void tCariPelatihFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCariPelatihFocusGained
        String placeholder = "Nama Pelatih";
        if (tCariPelatih.getText().equals(placeholder)) {
            tCariPelatih.setText("");
            tCariPelatih.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tCariPelatihFocusGained

    private void tCariPelatihFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCariPelatihFocusLost
        String placeholder = "Nama Pelatih";

        if (tCariPelatih.getText().isEmpty()) {
            tCariPelatih.setText(placeholder);
            tCariPelatih.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tCariPelatihFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExport;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCariPelatih;
    private javax.swing.JTable table_pelatih;
    // End of variables declaration//GEN-END:variables
}
