/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Color;
import kelas.Sabuk;
import kelas.anggota;
import kelas.koneksi;

/**
 *
 * @author Sukma Nur
 */
public class popUpDataAnggota extends javax.swing.JFrame {

    String idSabukTerpilih;

    /**
     * Creates new form popUpDataAnggota
     */
    private panelAnggota panel_anggota;

    public popUpDataAnggota(panelAnggota FpanelAnggota) {
        initComponents();
        loadSabuk();
        this.panel_anggota = FpanelAnggota;
        
        //jTanggalGabung.setMinSelectableDate(null);
        //jTanggalGabung.setMaxSelectableDate(null);
        //jTanggalGabung.getDateEditor().getUiComponent().setForeground(Color.BLACK);

        Sabuk sb = new Sabuk();
        sb.comboSabuk(cNamaSabuk);

        anggota ag = new anggota();
        ag.autoID(tIDAnggota);
    }

    public void setData(String id, String nama, String ttl, String jenis_kelamin,
            String status, String tahun_gabung, String sabuk) {
        tIDAnggota.setText(id);
        tNamaAnggota.setText(nama);

        //cek isi jk
        if ("L".equals(jenis_kelamin)) {
            cJenisKelamin.setSelectedItem("Laki-Laki");
        } else if ("P".equals(jenis_kelamin)) {
            cJenisKelamin.setSelectedItem("Perempuan");
        }

        cStatus.setSelectedItem(status);
        jTanggalGabung.setMinSelectableDate(new Date());// jika disable tanggal sblm harii ini
        cNamaSabuk.setSelectedItem(sabuk);

        // Format tanggal sesuai yang disimpan di database
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            if (ttl != null && !ttl.isEmpty()) {
                Date dateMulai = sdf.parse(ttl);
                jTanggalLahir.setDate(dateMulai);
            } else {
                jTanggalLahir.setDate(null);
            }

            if (tahun_gabung != null && !tahun_gabung.isEmpty()) {
                Date dateAkhir = sdf.parse(tahun_gabung);
                jTanggalGabung.setDate(dateAkhir);
            } else {
                jTanggalGabung.setDate(null);
            }

        } catch (Exception e) {
            e.printStackTrace();
            // Jika parsing gagal, kosongkan JDateChooser agar tidak error
            jTanggalLahir.setDate(null);
            jTanggalGabung.setDate(null);
        }
    }

    public void modeTambah() {
        jUbah.setVisible(false);
        jHapus.setVisible(false);
    }

    public void modeEdit() {
        jSimpan.setVisible(false);
    }

    public void loadSabuk() {
        try {
            Connection conn = new koneksi().configDB();
            String sql = "SELECT ID_sabuk, nama_sabuk FROM sabuk";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            cNamaSabuk.removeAllItems();
            while (rs.next()) {
                cNamaSabuk.addItem(rs.getString("nama_sabuk"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSimpan = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jUbah = new javax.swing.JButton();
        jKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tIDAnggota = new javax.swing.JTextField();
        tNamaAnggota = new javax.swing.JTextField();
        cJenisKelamin = new javax.swing.JComboBox<>();
        jTanggalLahir = new com.toedter.calendar.JDateChooser();
        cStatus = new javax.swing.JComboBox<>();
        jTanggalGabung = new com.toedter.calendar.JDateChooser();
        cNamaSabuk = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 240, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(469, 678));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Anggota");

        jSimpan.setBackground(new java.awt.Color(51, 102, 255));
        jSimpan.setForeground(new java.awt.Color(255, 255, 255));
        jSimpan.setText("Simpan");
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });

        jHapus.setBackground(new java.awt.Color(204, 0, 51));
        jHapus.setForeground(new java.awt.Color(255, 255, 255));
        jHapus.setText("Hapus");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });

        jUbah.setBackground(new java.awt.Color(255, 153, 51));
        jUbah.setText("Ubah");
        jUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUbahActionPerformed(evt);
            }
        });

        jKembali.setBackground(new java.awt.Color(153, 153, 153));
        jKembali.setForeground(new java.awt.Color(255, 255, 255));
        jKembali.setText("Kembali");
        jKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKembaliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama Anggota");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tanggal Lahir");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Status");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tanggal Gabung");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Nama Sabuk");

        tIDAnggota.setPreferredSize(new java.awt.Dimension(64, 35));

        tNamaAnggota.setPreferredSize(new java.awt.Dimension(64, 35));

        cJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cJenisKelamin.setPreferredSize(new java.awt.Dimension(72, 35));

        jTanggalLahir.setPreferredSize(new java.awt.Dimension(88, 35));

        cStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warga", "Siswa" }));
        cStatus.setPreferredSize(new java.awt.Dimension(72, 35));

        jTanggalGabung.setPreferredSize(new java.awt.Dimension(88, 35));

        cNamaSabuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNamaSabukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jKembali)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tIDAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tNamaAnggota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cJenisKelamin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTanggalLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(cStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cNamaSabuk, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTanggalGabung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jUbah)
                        .addGap(18, 18, 18)
                        .addComponent(jSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tIDAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTanggalGabung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cNamaSabuk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jKembali)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUbahActionPerformed
        // TODO add your handling code here:
        anggota ang = new anggota();

        ang.setId_anggota(tIDAnggota.getText());
        ang.setNama_anggota(tNamaAnggota.getText());
        ang.setStatus(cStatus.getSelectedItem().toString());
        String jk;
        if (cJenisKelamin.getSelectedItem().toString().equals("Laki-Laki")) {
            jk = "L";
        } else {
            jk = "P";
        }
        ang.setJenis_kelamin(jk);

        Date tglLahir = jTanggalLahir.getDate();
        String tglLahirDate = null;
        if (tglLahir != null) {
            tglLahirDate = new SimpleDateFormat("yyyy-MM-dd").format(tglLahir);
        }
        ang.setTgl_lahir(tglLahirDate);

        Date tanggalGab = jTanggalGabung.getDate();
        String tanggalGabDate = null;
        if (tanggalGab != null) {
            tanggalGabDate = new SimpleDateFormat("yyyy-MM-dd").format(tanggalGab);
        }
        ang.setTgl_gabung(tanggalGabDate);

        ang.setId_sabuk(idSabukTerpilih);

        ang.ubahanggota();

        if (panel_anggota != null) {
            panel_anggota.tampildataanggota();
        }
        dispose();


    }//GEN-LAST:event_jUbahActionPerformed

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        // TODO add your handling code here:
        anggota ang = new anggota();
        ang.setId_anggota(tIDAnggota.getText());
        ang.setNama_anggota(tNamaAnggota.getText());
        String jk;
        if (cJenisKelamin.getSelectedItem().toString().equals("Laki-Laki")) {
            jk = "L";
        } else {
            jk = "P";
        }
        ang.setJenis_kelamin(jk);

        ang.setStatus(cStatus.getSelectedItem().toString());

        Date tglLahir = jTanggalLahir.getDate();
        String tglLahirDate = null;
        if (tglLahir != null) {
            tglLahirDate = new SimpleDateFormat("yyyy-MM-dd").format(tglLahir);
        }
        ang.setTgl_lahir(tglLahirDate);

        Date tanggalGab = jTanggalGabung.getDate();
        String tanggalGabDate = null;
        if (tanggalGab != null) {
            tanggalGabDate = new SimpleDateFormat("yyyy-MM-dd").format(tanggalGab);
        }
        ang.setTgl_gabung(tanggalGabDate);

        ang.setId_sabuk(idSabukTerpilih);

        ang.tambahanggota();
        if (panel_anggota != null) {
            panel_anggota.tampildataanggota();
        }
        dispose();

    }//GEN-LAST:event_jSimpanActionPerformed

    private void jKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jKembaliActionPerformed

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        // TODO add your handling code here:
        anggota ang = new anggota();
        ang.setId_anggota(tIDAnggota.getText());

        ang.hapusanggota();
        if (panel_anggota != null) {
            panel_anggota.tampildataanggota();
        }
        dispose();

    }//GEN-LAST:event_jHapusActionPerformed

    private void cNamaSabukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNamaSabukActionPerformed
        // TODO add your handling code here:
        try {
            String nama = cNamaSabuk.getSelectedItem().toString();

            Connection conn = new koneksi().configDB();
            String sql = "SELECT ID_sabuk FROM sabuk WHERE nama_sabuk=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                idSabukTerpilih = rs.getString("ID_sabuk");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_cNamaSabukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUpDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUpDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUpDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUpDataAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new popUpDataAnggota().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cJenisKelamin;
    private javax.swing.JComboBox<String> cNamaSabuk;
    private javax.swing.JComboBox<String> cStatus;
    private javax.swing.JButton jHapus;
    private javax.swing.JButton jKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSimpan;
    private com.toedter.calendar.JDateChooser jTanggalGabung;
    private com.toedter.calendar.JDateChooser jTanggalLahir;
    private javax.swing.JButton jUbah;
    private javax.swing.JTextField tIDAnggota;
    private javax.swing.JTextField tNamaAnggota;
    // End of variables declaration//GEN-END:variables
}
