/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelas.registrasi;

/**
 *
 * @author HP
 */
public class popUpTambahRegistrasi extends javax.swing.JFrame {

    /**
     * Creates new form popUp_tambah_registrasi
     */
    DefaultTableModel modelRegistrasi;
    ArrayList<String[]> daftarAnggota = new ArrayList<>();

    public popUpTambahRegistrasi(String idRegis) {
        initComponents();
        setTableModel();
        
        if(lbIDdetailRegistrasi != null){
            registrasi regis = new registrasi();
        regis.autoIDDetail(lbIDdetailRegistrasi);
        }
        
    }

    void reset() {
        t_id.setText("");
        t_nama.setText("");
        t_status.setText("");
    }

    void setTableModel() {
        modelRegistrasi = new DefaultTableModel(new String[]{
            "No",
            "ID Anggota",
            "Nama Anggota",
            "Status"},
                0);
        table_peserta.setModel(modelRegistrasi);
    }

    public void tampilData(String id, String nama, String status) {
        t_id.setText(id);
        t_nama.setText(nama);
        t_status.setText(status);
    }

    public void namaKegiatan(String namaKegiatan) {
        lbNamaKegiatan.setText(
                namaKegiatan == null ? "" : namaKegiatan
        );
    }

    String konversiID(String namaRegis) {
        String id = "";
        try {
            registrasi regis = new registrasi();
            id = regis.konversIDRegis(namaRegis);
        } catch (Exception e) {
            System.out.println(e);
            return "";
        }
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_dasar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_cari = new javax.swing.JButton();
        t_id = new javax.swing.JTextField();
        t_nama = new javax.swing.JTextField();
        t_status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_peserta = new javax.swing.JTable();
        b_simpan = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        bDetail = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbIDdetailRegistrasi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNamaKegiatan = new javax.swing.JLabel();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_dasar.setBackground(new java.awt.Color(250, 240, 230));
        pn_dasar.setPreferredSize(new java.awt.Dimension(484, 539));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DAFTAR REGISTRASI PESERTA UJIAN PORSIGAL ");

        b_cari.setText("Cari Data Anggota");
        b_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cariActionPerformed(evt);
            }
        });

        t_id.setBorder(javax.swing.BorderFactory.createTitledBorder("ID Anggota"));

        t_nama.setBorder(javax.swing.BorderFactory.createTitledBorder("Nama Anggota"));
        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });

        t_status.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        table_peserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_peserta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pesertaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_peserta);

        b_simpan.setBackground(new java.awt.Color(0, 255, 51));
        b_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_simpan.setForeground(new java.awt.Color(255, 255, 255));
        b_simpan.setText("Save");
        b_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanActionPerformed(evt);
            }
        });

        bAdd.setBackground(new java.awt.Color(0, 204, 255));
        bAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAdd.setForeground(new java.awt.Color(255, 255, 255));
        bAdd.setText("Add");
        bAdd.setToolTipText("");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bDetail.setBackground(new java.awt.Color(153, 153, 153));
        bDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bDetail.setForeground(new java.awt.Color(255, 255, 255));
        bDetail.setText("Detail");
        bDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDetailActionPerformed(evt);
            }
        });

        bBack.setBackground(new java.awt.Color(255, 0, 102));
        bBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bBack.setForeground(new java.awt.Color(255, 255, 255));
        bBack.setText("<Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Detail Registrasi  :");

        lbIDdetailRegistrasi.setText("........");

        jLabel3.setText("Nama Kegiatan       :");

        lbNamaKegiatan.setText("........");

        bHapus.setText("Delete");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setText("Edit");
        bUbah.setToolTipText("");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dasarLayout.createSequentialGroup()
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_dasarLayout.createSequentialGroup()
                                .addComponent(bBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bDetail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_simpan))
                            .addGroup(pn_dasarLayout.createSequentialGroup()
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b_cari)
                                    .addGroup(pn_dasarLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbIDdetailRegistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn_dasarLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbNamaKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_dasarLayout.createSequentialGroup()
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bAdd)
                                    .addComponent(bHapus)
                                    .addComponent(bUbah))))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dasarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(73, 73, 73))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbIDdetailRegistrasi))
                .addGap(18, 18, 18)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbNamaKegiatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(b_cari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpan)
                    .addComponent(bDetail)
                    .addComponent(bBack))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dasar, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dasar, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void b_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanActionPerformed
        registrasi regis = new registrasi();

        regis.setIdDetailRegistrasi(lbIDdetailRegistrasi.getText());
        regis.setIdRegitrasi(konversiID(lbNamaKegiatan.getText()));

        boolean status = true;
        try {
            for (String[] item : daftarAnggota) {
                String namaAnggota = item[1];

                regis.konversiIDAnggota(namaAnggota, status);
            }
            if (status) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
            }

            // 🧹 Reset daftarAnggota agar kosong untuk input berikutnya
            daftarAnggota.clear();

            // 🧹 Reset tampilan tabel (hapus semua baris)
            DefaultTableModel model = (DefaultTableModel) table_peserta.getModel();
            model.setRowCount(0);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_b_simpanActionPerformed

    private void b_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cariActionPerformed
        new popUpCariAnggota(this).setVisible(true);
    }//GEN-LAST:event_b_cariActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        String id = t_id.getText();
        String nama = t_nama.getText();
        String status = t_status.getText();
        daftarAnggota.add(new String[]{
            id, nama, status
        });
        modelRegistrasi.addRow(new Object[]{
            modelRegistrasi.getRowCount() + 1,
            id, nama, status
        });
        reset();
    }//GEN-LAST:event_bAddActionPerformed

    private void bDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDetailActionPerformed
        String idRegis = konversiID(lbNamaKegiatan.getText()); // ambil ID registrasi dari label

        popUpDataRegistrasi detail_regis = new popUpDataRegistrasi(); // kirim ke frame kedua
        detail_regis.setVisible(true);
        detail_regis.tampilData(idRegis);
    }//GEN-LAST:event_bDetailActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        dispose();
    }//GEN-LAST:event_bBackActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        int row = table_peserta.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
            return;
        }

        String id = t_id.getText();
        String nama = t_nama.getText();
        String status = t_status.getText();

        // Update JTable
        modelRegistrasi.setValueAt(id, row, 1);
        modelRegistrasi.setValueAt(nama, row, 2);
        modelRegistrasi.setValueAt(status, row, 3);

        // Update ArrayList (data sementara)
        daftarAnggota.set(row, new String[]{id, nama, status});

        reset();
    }//GEN-LAST:event_bUbahActionPerformed

    private void table_pesertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pesertaMouseClicked
        int barisDipilih = table_peserta.rowAtPoint(evt.getPoint());

        //ambil nilai 
        String idAnggota = table_peserta.getValueAt(barisDipilih, 1).toString();
        String namaAnggta = table_peserta.getValueAt(barisDipilih, 2).toString();
        String status = table_peserta.getValueAt(barisDipilih, 3).toString();

        //tampilkan  ke textField 
        t_id.setText(idAnggota);
        t_nama.setText(namaAnggta);
        t_status.setText(status);
    }//GEN-LAST:event_table_pesertaMouseClicked

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int row = table_peserta.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Yakin ingin menghapus data ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            modelRegistrasi.removeRow(row);
            daftarAnggota.remove(row);
            reset();
        }
    }//GEN-LAST:event_bHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUpTambahRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUpTambahRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUpTambahRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUpTambahRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new popUpTambahRegistrasi().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bDetail;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bUbah;
    private javax.swing.JButton b_cari;
    private javax.swing.JButton b_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIDdetailRegistrasi;
    private javax.swing.JLabel lbNamaKegiatan;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_status;
    private javax.swing.JTable table_peserta;
    // End of variables declaration//GEN-END:variables
}
