/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.text.SimpleDateFormat;
import java.util.Date;
import kelas.prestasi;
import tampilan.panelPrestasi;

/**
 *
 * @author This PC
 */
public class popUpTambahPrestasi extends javax.swing.JFrame {

    /**
     * Creates new form popUp_tambahPrestasi
     */
    private panelPrestasi panelPrestasi;
    
    public popUpTambahPrestasi(panelPrestasi panelPrestasi) {
        initComponents();
        this.panelPrestasi = panelPrestasi;
       
        
        prestasi ps = new prestasi();
        ps.autoID(t_idprestasi);
        ps.comboanggota(cnamaanggota);
    }
    
    void reset(){
        t_idprestasi.setText(null);
        cnamaanggota.setSelectedItem(null);
        ctingkat.setSelectedItem(null);
        
    }
    
    public void setData(String idPrestasi, String peringkat, String tgl, String namaAnggota,String tingkat){
        t_idprestasi.setText(idPrestasi);
        tPeringkat.setText(peringkat);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            if(tgl != null && !tgl.isEmpty()){
                Date date = sdf.parse(tgl);
                tTgl.setDate(date);
            }else{
                tTgl.setDate(null);
            }
        } catch (Exception e) {
            e.printStackTrace();
            tTgl.setDate(null);
        }
        
        cnamaanggota.setSelectedItem(namaAnggota);
        ctingkat.setSelectedItem(tingkat);
    }
    
    String konversiID(String namaanggota){
    String id = "";
    try{
    prestasi ps = new prestasi();
    id = ps.konversID_anggota(namaanggota);
    }catch (Exception e){
        System.out.println(e);
    }
    return id;
    }
    
    public void tampilanTambah(){
        b_ubah.setVisible(false);
        b_hapus.setVisible(false);
    }
    
    public void tampilanUbah(){
        b_simpan.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_idprestasi = new javax.swing.JTextField();
        ctingkat = new javax.swing.JComboBox<>();
        b_simpan = new javax.swing.JButton();
        b_kembali = new javax.swing.JButton();
        b_ubah = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        cnamaanggota = new javax.swing.JComboBox<>();
        tPeringkat = new javax.swing.JTextField();
        tTgl = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 240, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("EDIT DATA PRESTASI ");

        t_idprestasi.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ctingkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kecamatan", "Kabupaten", "Provinsi", "Nasional", "Internasional" }));
        ctingkat.setBorder(javax.swing.BorderFactory.createTitledBorder("Tingkat"));

        b_simpan.setBackground(new java.awt.Color(0, 0, 255));
        b_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_simpan.setForeground(new java.awt.Color(255, 255, 255));
        b_simpan.setText("Simpan");
        b_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanActionPerformed(evt);
            }
        });

        b_kembali.setBackground(new java.awt.Color(0, 255, 102));
        b_kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_kembali.setForeground(new java.awt.Color(255, 255, 255));
        b_kembali.setText("Kembali");
        b_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kembaliActionPerformed(evt);
            }
        });

        b_ubah.setBackground(new java.awt.Color(255, 204, 0));
        b_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_ubah.setForeground(new java.awt.Color(255, 255, 255));
        b_ubah.setText("Ubah");
        b_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ubahActionPerformed(evt);
            }
        });

        b_hapus.setBackground(new java.awt.Color(255, 51, 0));
        b_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_hapus.setForeground(new java.awt.Color(255, 255, 255));
        b_hapus.setText("Hapus");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        cnamaanggota.setBorder(javax.swing.BorderFactory.createTitledBorder("Nama Anggota"));

        tPeringkat.setBorder(javax.swing.BorderFactory.createTitledBorder("Peringkat"));

        tTgl.setBorder(javax.swing.BorderFactory.createTitledBorder("Tanggal Peroleh"));

        jLabel2.setText("ID Prestasi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(t_idprestasi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tPeringkat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(159, 159, 159)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(b_simpan)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(b_kembali))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(b_ubah)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(ctingkat, javax.swing.GroupLayout.Alignment.LEADING, 0, 324, Short.MAX_VALUE)
                                .addComponent(cnamaanggota, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tTgl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_idprestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tPeringkat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tTgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(cnamaanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ctingkat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpan)
                    .addComponent(b_kembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ubah)
                    .addComponent(b_hapus))
                .addGap(137, 137, 137))
        );

        t_idprestasi.getAccessibleContext().setAccessibleName("ID prestasi\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanActionPerformed
        // TODO add your handling code here:
        prestasi pres = new prestasi();
        pres.setID_prestasi(t_idprestasi.getText());
        pres.setPeringkat(tPeringkat.getText());
        pres.setTingkat(ctingkat.getSelectedItem().toString());
       
        //ambil tgl
        Date tgl = tTgl.getDate();
        String tanggal = null;
        if(tgl !=null){
            tanggal = new SimpleDateFormat("yyyy-MM-dd").format(tgl);
        }
        pres.setTgl(tanggal);
        pres.setID_anggota(konversiID(cnamaanggota.getSelectedItem().toString()));
        
        pres.tambah_prestasi();
        
        if(panelPrestasi != null){
           panelPrestasi.load_table_prestasi();
        }
        reset();
        dispose();
    }//GEN-LAST:event_b_simpanActionPerformed

    private void b_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ubahActionPerformed
        // TODO add your handling code here:
         prestasi pres = new prestasi();
        pres.setID_prestasi(t_idprestasi.getText());
        pres.setPeringkat(tPeringkat.getText());
        pres.setTingkat(ctingkat.getSelectedItem().toString());
       
        //ambil tgl
        Date tgl = tTgl.getDate();
        String tanggal = null;
        if(tgl !=null){
            tanggal = new SimpleDateFormat("yyyy-MM-dd").format(tgl);
        }
        pres.setTgl(tanggal);
        pres.setID_anggota(konversiID(cnamaanggota.getSelectedItem().toString()));
        
        pres.ubah_prestasi();
        if(panelPrestasi != null){
            panelPrestasi.load_table_prestasi();
        }
        reset();
        dispose();
    }//GEN-LAST:event_b_ubahActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        // TODO add your handling code here:
         prestasi pres = new prestasi();
        pres.setID_prestasi(t_idprestasi.getText());
        
        pres.hapus_prestasi();
        if(panelPrestasi != null){
            panelPrestasi.load_table_prestasi();
        }
        reset();
        dispose();
    }//GEN-LAST:event_b_hapusActionPerformed

    private void b_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_b_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUpTambahPrestasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUpTambahPrestasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUpTambahPrestasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUpTambahPrestasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new popUp_tambahPrestasi().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new popUp_tambahPrestasi().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new popUp_tambahPrestasi().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new popUp_tambahPrestasi().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_kembali;
    private javax.swing.JButton b_simpan;
    private javax.swing.JButton b_ubah;
    private javax.swing.JComboBox<String> cnamaanggota;
    private javax.swing.JComboBox<String> ctingkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tPeringkat;
    private com.toedter.calendar.JDateChooser tTgl;
    private javax.swing.JTextField t_idprestasi;
    // End of variables declaration//GEN-END:variables
}
