/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import kelas.registrasi;
import kelas.ujian;

/**
 *
 * @author HP
 */
public class poUpTambahDataRegistrasi extends javax.swing.JFrame {

    /**
     * Creates new form poUpTambahDataRegistrasi
     */
    private panelRegistrasi pRegistrasi;

    public poUpTambahDataRegistrasi(panelRegistrasi pRegis) {
        initComponents();
        this.pRegistrasi = pRegis;
    }

    void reset() {
        t_nama.setText(null);
        t_tgl_mulai.setCalendar(null);
        t_tgl_selesai.setCalendar(null);
        t_lokasi.setText(null);
        cMainEvent.setSelectedIndex(0);
    }

    String konversiID(String namaUjian) {
        String id = "";
        try {
            ujian uj = new ujian();
            id = uj.getIdKegiatanByName(namaUjian);
        } catch (Exception e) {
            System.out.println(e);
            return "";
        }
        return id;
    }

    public void tampilan_tambah_regist() {
        b_ubah.setVisible(false);
        b_hapus.setVisible(false);
//        tentukanJenis();
    }

    public void tampilan_edit_regist() {
        b_simpan.setVisible(false);
    }

    public void tampil_data(String id, String nama, String tglMulai, String tglAkhir,
            String lokasi, String ujian) {

        t_idregist.setText(id);
        t_nama.setText(nama);

        // Format tanggal sesuai yang disimpan di database
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            if (tglMulai != null && !tglMulai.isEmpty()) {
                Date dateMulai = sdf.parse(tglMulai);
                t_tgl_mulai.setDate(dateMulai);
            } else {
                t_tgl_mulai.setDate(null);
            }

            if (tglAkhir != null && !tglAkhir.isEmpty()) {
                Date dateAkhir = sdf.parse(tglAkhir);
                t_tgl_selesai.setDate(dateAkhir);
            } else {
                t_tgl_selesai.setDate(null);
            }

        } catch (ParseException e) {
            e.printStackTrace();
            // Jika parsing gagal, kosongkan JDateChooser agar tidak error
            t_tgl_mulai.setDate(null);
            t_tgl_selesai.setDate(null);
        }

        t_lokasi.setText(lokasi);
        cMainEvent.setSelectedItem(ujian);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        t_idregist = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t_tgl_mulai = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        t_tgl_selesai = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        t_lokasi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cMainEvent = new javax.swing.JComboBox<>();
        b_simpan = new javax.swing.JButton();
        b_ubah = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 240, 230));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nama Kegiatan ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tanggal Mulai");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tanggal Selesai");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Lokasi");

        t_lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_lokasiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Kegiatan Utama");

        b_simpan.setBackground(new java.awt.Color(0, 204, 0));
        b_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_simpan.setForeground(new java.awt.Color(255, 255, 255));
        b_simpan.setText("Simpan");
        b_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanActionPerformed(evt);
            }
        });

        b_ubah.setBackground(new java.awt.Color(255, 102, 0));
        b_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_ubah.setForeground(new java.awt.Color(255, 255, 255));
        b_ubah.setText("Ubah");
        b_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ubahActionPerformed(evt);
            }
        });

        b_hapus.setBackground(new java.awt.Color(255, 51, 51));
        b_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_hapus.setForeground(new java.awt.Color(255, 255, 255));
        b_hapus.setText("Hapus");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("REGISTRASI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(b_ubah)
                        .addGap(18, 18, 18)
                        .addComponent(b_hapus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(324, 324, 324))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cMainEvent, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_tgl_selesai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_tgl_mulai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_nama, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_idregist, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_lokasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_idregist, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_tgl_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_tgl_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cMainEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpan)
                    .addComponent(b_ubah)
                    .addComponent(b_hapus))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_lokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_lokasiActionPerformed

    private void b_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanActionPerformed
        registrasi regis = new registrasi();
        regis.setIdRegitrasi(t_idregist.getText());
        regis.setNamaRegistrasi(t_nama.getText());

        //ambil tgl mulai dari komponen kalender
        Date tglMulaiDate = t_tgl_mulai.getDate();
        String tglMulai = null;
        if (tglMulaiDate != null) {
            // Mengubah tanggal lahir menjadi format "yyyy-MM-dd"
            tglMulai = new SimpleDateFormat("yyyy-MM-dd").format(tglMulaiDate);
        }
        regis.setTglmulai(tglMulai);

        //ambil tgl mulai dari komponen kalender
        Date tglAkhirDate = t_tgl_selesai.getDate();
        String tglAkhir = null;
        if (tglAkhirDate != null) {
            // Mengubah tanggal lahir menjadi format "yyyy-MM-dd"
            tglAkhir = new SimpleDateFormat("yyyy-MM-dd").format(tglAkhirDate);
        }
        regis.setTglSelesai(tglAkhir);

        regis.setLokasi(t_lokasi.getText());
        regis.setParentUjian(konversiID(cMainEvent.getSelectedItem().toString()));
//        event.setiD_user("US01");

        regis.tambahRegis();
        // setelah berhasil tambah, refresh tabel di frame utama
        if (pRegistrasi != null) {
            pRegistrasi.load_table_regis();// panggil fungsi reload
        }
        reset();
        dispose();
    }//GEN-LAST:event_b_simpanActionPerformed

    private void b_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ubahActionPerformed
        registrasi regis = new registrasi();
        regis.setIdRegitrasi(t_idregist.getText());
        regis.setNamaRegistrasi(t_nama.getText());

        //ambil tgl mulai dari komponen kalender
        Date tglMulaiDate = t_tgl_mulai.getDate();
        String tglMulai = null;
        if (tglMulaiDate != null) {
            // Mengubah tanggal lahir menjadi format "yyyy-MM-dd"
            tglMulai = new SimpleDateFormat("yyyy-MM-dd").format(tglMulaiDate);
        }
        regis.setTglmulai(tglMulai);

        //ambil tgl mulai dari komponen kalender
        Date tglAkhirDate = t_tgl_selesai.getDate();
        String tglAkhir = null;
        if (tglAkhirDate != null) {
            // Mengubah tanggal lahir menjadi format "yyyy-MM-dd"
            tglAkhir = new SimpleDateFormat("yyyy-MM-dd").format(tglAkhirDate);
        }
        regis.setTglSelesai(tglAkhir);

        regis.setLokasi(t_lokasi.getText());
        regis.setParentUjian(konversiID(cMainEvent.getSelectedItem().toString()));
//        event.setiD_user("US01");

        regis.ubahRegis();
        // setelah berhasil tambah, refresh tabel di frame utama
        if (pRegistrasi != null) {
            pRegistrasi.load_table_regis();// panggil fungsi reload
        }
        reset();
        dispose();
    }//GEN-LAST:event_b_ubahActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        registrasi regis = new registrasi();
        regis.setIdRegitrasi(t_idregist.getText());
        regis.hapusRegis();
    }//GEN-LAST:event_b_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(poUpTambahDataRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(poUpTambahDataRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(poUpTambahDataRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(poUpTambahDataRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new poUpTambahDataRegistrasi().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_simpan;
    private javax.swing.JButton b_ubah;
    private javax.swing.JComboBox<String> cMainEvent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t_idregist;
    private javax.swing.JTextField t_lokasi;
    private javax.swing.JTextField t_nama;
    private com.toedter.calendar.JDateChooser t_tgl_mulai;
    private com.toedter.calendar.JDateChooser t_tgl_selesai;
    // End of variables declaration//GEN-END:variables
}
